version: "3.8"
services:

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ${PWD}/scripts/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:ro
    healthcheck:
      test: pg_isready --username=postgres
      interval: 1s
      retries: 100

  app:
    depends_on:
      postgres:
        condition: service_healthy
    build: .
    ports:
      - 3000:3000
    environment:
      PG_DATABASE: modelling02
      PG_HOST: postgres
      PG_PASSWORD: password
      PG_PORT: 5432
      PG_SSL: false
      PG_USER: postgres
